directories:
  output: release/${version}
  buildResources: build
$schema: https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json
appId: com.empresa.carteradashboard
asar: true
productName: Cartera Dashboard
npmRebuild: false
buildDependenciesFromSource: false
copyright: Copyright Â© 2026
files:
  - filter:
      - dist
      - dist-electron
      - '!node_modules'
      - '!src'
      - '!electron'
      - '!*.md'
      - '!.vscode'
mac:
  target:
    - dmg
  category: public.app-category.business
  icon: build/icon.icns
  artifactName: ${productName}-Mac-${version}-Installer.${ext}
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
  artifactName: ${productName}-Windows-${version}-Setup.${ext}
  publisherName: Tu Empresa
  verifyUpdateCodeSignature: false
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
linux:
  target:
    - AppImage
  artifactName: ${productName}-Linux-${version}.${ext}
electronVersion: 30.5.1
